Repository GDGoC-SucceSS-Team15/Parker_Frontend, pull requests merged in 2025-02, with the labels that each got.

#8 [feature/parkinginfo] 신고 모달 구현 및 적용
  src/components/BottomBar.jsx
  src/components/Modals/CustomModal.jsx
  src/components/Modals/ReportContent.jsx
  src/pages/MyParkingPage.jsx
Labels: ✨ feature

#11 [api/signin signup] 회원가입/로그인, 주차장데이터 api 연동
  package-lock.json
  package.json
  src/api/api.js
  src/api/map.js
  src/api/parkingSpace.js
  src/assets/NewParkingMarker.svg
  src/components/List/ParkInfoListItem.jsx
  src/components/Map.jsx
  src/components/Modals/ParkInfoContent.jsx
  src/components/Modals/ParkingMarkerContent.jsx
  src/components/TopBar.jsx
  src/hooks/useCurrentLocation.js
  src/hooks/useDayType.js
  src/index.css
  src/pages/ParkInfoPage.jsx
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
  yarn.lock
Labels: ⚠️ bugfix, 📥 api

#12 [api/report] 신고 api 연동
  src/api/report.js
  src/components/Modals/ReportContent.jsx
  src/pages/ReportPage.jsx
Labels: ✨ feature, 📥 api

#13 [feature/ai uploadmodal] 단속 여부 확인-이미지 업로드 모달 구현
  src/assets/image.svg
  src/assets/uploadImg.svg
  src/assets/warning.svg
  src/components/Ai/UploadModal.jsx
  src/components/TopBar.jsx
Labels: ✨ feature

#15 [Api/report] 리팩토링 및 즐겨찾기 연동
  .gitignore
  package.json
  src/api/bookmark.js
  src/api/map.js
  src/api/user.js
  src/components/Map.jsx
  src/components/Modals/ParkingMarkerContent.jsx
  src/hooks/useCheckClosed.js
  src/pages/BookmarkPage.jsx
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
Labels: 📥 api, 🛠️ refactor

#16 [Api/mypage] 마이페이지 연동
  src/api/mypage.js
  src/api/profileEdit.js
  src/pages/MyPage.jsx
  src/pages/NicknamePage.jsx
Labels: 📥 api

#14 [feature/enforcement result] 단속 여부 확인 - 결과 표시 모달 구현
  src/App.js
  src/components/Ai/Result/ResultModal.jsx
  src/pages/TestPage.jsx
Labels: ✨ feature

#18 [api/mypage] 마이페이지 코드 수정
  src/pages/MyPage.jsx
Labels: 📥 api, 🛠️ refactor

#22 [dev-main] 배포
  .gitignore
  package-lock.json
  package.json
  public/index.html
  public/logo.png
  public/thumbnail.png
  src/App.css
  src/App.js
  src/api/ai.js
  src/api/api.js
  src/api/crackdown.js
  src/api/map.js
  src/api/mypage.js
  src/api/profileEdit.js
  src/assets/Bottom_Button/BT_Crackdown.svg
  src/assets/CrackdownMarker.svg
  src/assets/MenuButton/Menu_Crackdown.svg
  src/assets/ParkingIcon.svg
  src/assets/parker_loading.gif
  src/components/Ai/Result/ResultModal.jsx
  src/components/Ai/UploadModal.jsx
  src/components/BottomBar.jsx
  src/components/List/CrackdownListItem.jsx
  src/components/Loading/Loading.jsx
  src/components/Map.jsx
  src/components/Menu.jsx
  src/components/Modals/MarkerModal.jsx
  src/components/Modals/ParkingMarkerContent.jsx
  src/components/Modals/ReportContent.jsx
  src/components/Notification/Notification.jsx
  src/components/TopBar.jsx
  src/hooks/useCheckClosed.js
  src/pages/CrackdownPage.jsx
  src/pages/MainPage.jsx
  src/pages/MyPage.jsx
  src/pages/MyParkingPage.jsx
  src/pages/NicknamePage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/ReportPage.jsx
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
  src/pages/TestPage.jsx
  src/store/loadingStore.js
  src/store/notificationStore.js
  yarn.lock
Labels: 🌎 deploy

#23 [dev-main] chore: og image 변경
  public/index.html
Labels: 🌎 deploy

#25 [Fix/report bm] 검색 결과 마커 위치 기반 데이터 조회 구현 + 세부 오류 수정
  public/crackdown.svg
  public/parking.svg
  src/api/bookmark.js
  src/assets/CrackdownMarker.svg
  src/assets/ParkingMarker.svg
  src/assets/cctv.svg
  src/assets/parking.svg
  src/assets/warning.svg
  src/components/Ai/Result/ResultModal.jsx
  src/components/Ai/UploadModal.jsx
  src/components/Map.jsx
  src/components/Menu.jsx
  src/components/Modals/ReportContent.jsx
  src/components/TopBar.jsx
  src/pages/BookmarkPage.jsx
  src/pages/ReportPage.jsx
  src/styles/InfoWindow.css
Labels: ⚠️ bugfix, ✨ feature, 📥 api

#30 [fix/yeji] api 예외처리 및 화면 확대 방지, vh 변경
  public/index.html
  public/logo.png
  src/App.css
  src/api/api.js
  src/api/bookmark.js
  src/api/report.js
  src/api/user.js
  src/components/Ai/Result/ResultModal.jsx
  src/components/Headers/Header.jsx
  src/components/List/ParkInfoListItem.jsx
  src/components/Loading/Loading.jsx
  src/components/Modals/ParkInfoContent.jsx
  src/components/Modals/ParkingMarkerContent.jsx
  src/components/Modals/ReportContent.jsx
  src/components/TopBar.jsx
  src/pages/BookmarkPage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/ParkInfoPage.jsx
  src/pages/ReportPage.jsx
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
Labels: ⚠️ bugfix, 🛠️ refactor
